"""empty message

Revision ID: ef1e65e19d72
Revises: 
Create Date: 2021-05-19 20:39:15.951587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef1e65e19d72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cook_name', sa.String(length=50), nullable=False),
    sa.Column('ingredient', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cook')
    # ### end Alembic commands ###
